### ISSUE TITLE
What is this and why is is necessary? 

### ISSUE THREAD

**Issue by JustusAdam** [fsr/matthias#2] opened 2015-07-27 12:32 UTC
What is this?
What do we need it for?
Why is it using one of our precious private repositories?
And more importantly where is this bot running?

**Comment by kiliankoe** [comment] 2015-07-27 12:34
> What is this?

A [hubot](https://hubot.github.com) for our slack.

> What do we need it for?

As an awesome bot for our slack.

> Why is it using one of our precious private repositories?

Because we're not using them for anything else currently. I'll gladly move matthias elsewhere should this ever be a problem.

> And more importantly where is this bot running?

My server.

**Comment by JustusAdam** [comment] 2015-07-27 12:36
I feel slightly betrayed. To be honest.
I wrote a perfectly good bot from scratch that could have been extended easily if necessary.

**Comment by kiliankoe** [comment] 2015-07-27 12:37
I never intended to _betray_ you. Afaik your bot currently isn't running and was intended for bash integration, which is great! No reason not to use both :). Otherwise a custom bot like this with support for plugins that already exist offers a lot of great functionality.

**Comment by JustusAdam** [comment] 2015-07-27 12:39
It is! And it has been for days. 
Just because of this bot (and another project) I looked into deploying demons on uberspace to make sure it is running at all times.

**Comment by JustusAdam** [comment] 2015-07-27 12:39
It's much more customisable too. And far cooler, because haskell :stuck_out_tongue:

**Comment by JustusAdam** [comment] 2015-07-27 12:41
I almost got it to interpret haskell code snippets that you send him.

**Comment by kiliankoe** [comment] 2015-07-27 12:56
Any chance of moving this conversation to Slack as well? This is a private repo and we're only spamming people with notifications, which sucks.

**Closed as completed** 2015-07-27 15:16 UTC
